name: Running Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List Files in Directory
        run: ls -la

      - name: Running Test
        run: ./tests.sh
