name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Libraries
        run: |
          python3 -m pip install --upgrade pip
          pip install kaggle pandas matplotlib seaborn
    

      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}", "key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json

      - name: Make Shell executable
        run: chmod +x ./project/tests.sh
        
      - name: Run tests.sh
        run: ./project/tests.sh
